spring:
  profiles.active: ${env:local}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    connectionTestQuery: SELECT 1 FROM DUAL

mybatis:
  # A Configuration object for customize default settings.
  # If configLocation is specified, this property is not used.
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: kr.co.oliveyoung.shopapp.feature
  configuration:
    cacheEnabled: false
    useGeneratedKeys: true
    defaultExecutorType: REUSE
    aggressiveLazyLoading: false
---
spring:
  profiles: local
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/classicmodels?serverTimezone=UTC
    username: root
    password: vito0920
    maximumPoolSize: 3
---
spring:
  profiles: dev
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/classicmodels?serverTimezone=UTC
    username: root
    password: vito0920
    maximumPoolSize: 3
---
spring:
  profiles: test
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/classicmodels?serverTimezone=UTC
    username: root
    password: vito0920
    maximumPoolSize: 3
---
spring:
  profiles: stage
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/classicmodels?serverTimezone=UTC
    username: root
    password: vito0920
    maximumPoolSize: 3
---
spring:
  profiles: stage
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/classicmodels?serverTimezone=UTC
    username: root
    password: vito0920
    maximumPoolSize: 3
---
spring:
  profiles: production
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/classicmodels?serverTimezone=UTC
    username: root
    password: vito0920
    maximumPoolSize: 3
