spring:
  application:
    name: shop-app
  http:
    encoding:
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/public/

  profiles.active: ${env:local}
  oracle:
    datasource:
      driverClassName: oracle.jdbc.driver.OracleDriver
      connectionTestQuery: SELECT 1 FROM DUAL
  mysql:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      connectionTestQuery: SELECT 1 FROM DUAL

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: kr.co.oliveyoung.feature
  configuration:
    cacheEnabled: false
    useGeneratedKeys: true
    defaultExecutorType: REUSE
    aggressiveLazyLoading: false

server:
  port: ${PORT:9090}
  compression:
    enabled: true

logging:
  config: classpath:config/logback-config.xml

---
spring:
  profiles: local
  oracle:
    datasource:
      jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521/orcl
      username: test
      password: test
      maximumPoolSize: 20
  datasource-mongo:
    uri: 116.121.31.99:27017/?authSource=storeApp
    username: test
    password: test
  mysql:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test
      username: root
      password: root
---
spring:
  profiles: dev
  datasource-oracle:
    jdbcUrl: jdbc:oracle:thin:@52.2.165.125:1522/OYOODEV
    username: OOMAPP
    password: TAblet52()
    maximumPoolSize: 20
---
spring:
  profiles: test
---
spring:
  profiles: beta
---
spring:
  profiles: stage
---
spring:
  profiles: production